//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OdbcJdbcSetup.rc
//
#define IDD_DSN_PROPERTIES              129
#define IDC_NAME                        1000
#define IDC_DATABASE                    1001
#define IDC_FIND_FILE                   1002
#define IDC_USER                        1003
#define IDC_PASSWORD                    1004
#define IDC_CLIENT                      1005
#define IDC_DRIVER                      1006
#define IDC_ROLE                        1007
#define IDC_CHECK_READ                  1008
#define IDC_CHECK_NOWAIT                1009
#define IDC_CHARSET                     1010
#define IDC_FIND_FILE_CLIENT            1011
#define IDC_DIALECT3                    1012
#define IDC_DIALECT1                    1013
#define IDC_CHECK_QUOTED                1014
#define IDC_CHECK_SENSITIVE             1015
#define IDC_CHECK_AUTOQUOTED            1016
#define IDC_TEST_CONNECTION             1017
#define IDC_HELP_ODBC                   1018
#define IDC_DESCRIPTION                 1019
#define IDC_BUTTON_SERVICE              1020
#define IDC_SERVICE_TABCTRL             1021
#define IDC_CHECK_IGNORE_CHECKSUM       1022
#define IDC_CHECK_IGNORE_TRANS_LIMBO    1023
#define IDC_CHECK_ONLY_METADATA         1024
#define IDC_CHECK_NO_GARBAGE            1025
#define IDC_CHECK_OLD_METADATA          1026
#define IDC_CHECK_NO_TRANSPORTABLE      1027
#define IDC_CHECK_CONV_EXT_TABLE        1028
#define IDC_CHECK_NO_COMPRESS           1029
#define IDC_BLOCKING_FACTOR             1030
#define IDC_BACKUP_FILE                 1031
#define IDC_FIND_FILE_BACKUP            1032
#define IDC_BUTTON_VIEW_LOG             1033
#define IDC_EDIT_VIEW_LOG_LINE          1035
#define IDC_SIZE_BUFFERS                1036
#define IDC_CHECK_NO_INDEX              1037
#define IDC_CHECK_NO_SHADOW             1038
#define IDC_CHECK_NO_VALIDITY           1039
#define IDC_CHECK_REPLACE               1040
#define IDC_CHECK_FULL_SPACE            1041
#define IDC_CHECK_NO_READONLY           1042
#define IDC_CHECK_COMMIT                1043
#define IDC_COMBOBOX_PAGE_SIZE          1044
#define IDC_RADIO_VALIDATE_DB           1045
#define IDC_RADIO_SWEEP_DB              1046
#define IDC_RADIO_PREPARE_DB            1047
#define IDC_RADIO_LIST_LIMBO_TR         1048
#define IDC_RADIO_REPAIR_LIMBO_TR       1049
#define IDC_CHECK_KILL_SHADOWS          1050
#define IDC_CHECK_VALIDATE_RECORD       1051
#define IDC_CHECK_READONLY              1052
#define IDC_PROGRESS_BAR                1053
#define IDC_RADIO_SHOW_DATABASE_LOG     1054
#define IDC_RADIO_DATA_PAGES            1055
#define IDC_RADIO_HEADER_PAGES          1056
#define IDC_RADIO_INDEX_PAGES           1057
#define IDC_RADIO_SYS_RELATIONS         1058
#define IDC_RADIO_RECORD_VERSIONS       1059
#define IDC_RADIO_DATABASE_LOG          1060
#define IDC_RADIO_ALL_OPTIONS           1061
#define IDC_GROUPBOX_VALIDATE_OPTIONS   1062
#define IDC_USERS_TABCTRL               1063
#define IDC_USERS_LISTVIEW_LEFT         1064
#define IDC_USERS_LISTVIEW_RIGHT        1065
#define IDC_BUTTON_GET_INFO             1066
#define IDC_BUTTON_ADD_USER             1067
#define IDC_BUTTON_MOD_USER             1068
#define IDC_BUTTON_DEL_USER             1069
#define IDC_EDIT_USER_NAME              1070
#define IDC_EDIT_PASSWORD               1071
#define IDC_EDIT_CONF_PASSWORD          1072
#define IDC_EDIT_USER_FIRST_NAME        1073
#define IDC_EDIT_USER_MIDDLE_NAME       1074
#define IDC_EDIT_USER_LAST_NAME         1075
#define IDC_EDIT_USER_ID                1076
#define IDC_EDIT_GROUP_ID               1077
#define IDC_COMBOBOX_USE_SCHEMA         1078
#define IDC_LOCKTIMEOUT                 1079
#define IDC_STATIC_LOCKTIMEOUT          1080
#define IDC_CHECK_SFTHREAD              1081
#define IDC_STATIC                      -1

//
// ID for translate strings
//
#define IDS_DLG_TITLE_SETUP		0
#define IDS_BUTTON_FIND_FILE		1
#define IDS_CHECK_READ			2
#define IDS_CHECK_NOWAIT		3
#define IDS_BUTTON_OK			4
#define IDS_BUTTON_CANCEL		5
#define IDS_STATIC_DSN			6
#define IDS_STATIC_DESCRIPTION          7
#define IDS_STATIC_DATABASE		8
#define IDS_STATIC_ACCOUNT		9
#define IDS_STATIC_PASSWORD		10
#define IDS_STATIC_DRIVER		11
#define IDS_STATIC_ROLE			12
#define IDS_STATIC_CHARSET		13
#define IDS_GROUPBOX_OPTIONS		14
#define IDS_GROUPBOX_INIT_TRANSACTION	15
#define IDS_STATIC_CLIENT		16
#define IDS_GROUPBOX_DIALECT		17
#define IDS_GROUPBOX_EXT_PROPERTY	18
#define IDS_CHECK_QUOTED		19
#define IDS_CHECK_SENSITIVE		20
#define IDS_CHECK_AUTOQUOTED		21
#define IDS_BUTTON_TEST_CONNECTION	22
#define IDS_BUTTON_HELP_ODBC		23
#define IDS_DLG_TITLE_FINDFILE_DATABASE	24
#define IDS_DLG_TITLE_FINDFILE_CLIENT	25
#define IDS_MESSAGE_01			26
#define IDS_MESSAGE_02			27
#define IDS_ERROR_MESSAGE_01		28
#define IDS_ERROR_MESSAGE_02		29
#define IDS_ERROR_MESSAGE_03		30
#define IDS_ERROR_MESSAGE_04		31
#define IDS_ERROR_MESSAGE_05		32
#define IDS_ERROR_MESSAGE_06		33
#define IDS_ERROR_MESSAGE_07		34
#define IDS_ERROR_MESSAGE_08		35
#define IDS_ERROR_MESSAGE_09		36
#define IDS_ERROR_MESSAGE_10		37
#define IDS_ERROR_MESSAGE_11		38
#define IDS_ERROR_MESSAGE_12		39
#define IDS_ERROR_MESSAGE_13		40
#define IDS_ERROR_MESSAGE_14		41
#define IDS_ERROR_MESSAGE_15		42
#define IDS_ERROR_MESSAGE_16		43
#define IDS_ERROR_MESSAGE_17		44
#define IDS_ERROR_MESSAGE_18		45
#define IDS_ERROR_MESSAGE_19		46
#define IDS_ERROR_MESSAGE_20		47
#define IDS_BUTTON_SERVICES             48
#define IDS_USESCHEMA_NULL              49
#define IDS_USESCHEMA_DEL               50
#define IDS_USESCHEMA_FULL              51
#define IDS_STATIC_LOCKTIMEOUT          52
#define IDS_CHECK_SFTHREAD		53
#define IDS_BUTTON_CLOSE		54
