name: RaspberryPI

on:
  push:
    branches: [ "master", "new-build-system", "new-build-system-no-pr" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        copy_repository_path: /opt/fb_odbc
        copy_artifact_path: |
                    build/libOdbcFb.so
        commands: |
            sudo apt-get update
            sudo apt-get install -y cmake unixodbc unixodbc-dev
            cd /opt/fb_odbc
            cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
            cmake --build build --config Release
    
    - uses: actions/upload-artifact@v4
      with:
          name: linux_arm64_libs
          path: |
              libOdbcFb.so

