name: RaspberryPI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@v2
      with:
        copy_repository_path: /opt/fb_odbc
        copy_artifact_path: |
                    Builds/Gcc.lin/Release_*
                    !Builds/Gcc.lin/Release_*/obj
        copy_artifact_dest: /opt/fb_odbc_arts
        commands: |
            sudo apt-get install -y unixodbc unixodbc-dev
            cd /opt/fb_odbc/Builds/Gcc.lin
            cp makefile.linux makefile
            make
    
    - uses: actions/upload-artifact@v4
      with:
          name: linux_arm64_libs
          path: /opt/fb_odbc_arts

